apiVersion: v1
kind: Service
metadata:
  name: sleep-2-headless
spec:
  type: ClusterIP
  ports:
    - port: 80
---
kind: Endpoints
apiVersion: v1
metadata:
  name: sleep-2-headless
subsets:
  - addresses:
      - ip: 10.84.1.128
    ports:
      - port: 80
